// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Super_Market;

#nullable disable

namespace Super_Market.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230217225102_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Super_Market.Categorys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StorId");

                    b.ToTable("Categorys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dairy",
                            StorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Beverages",
                            StorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vegetables",
                            StorId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Personal Care",
                            StorId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Meat",
                            StorId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Pasta/Rice",
                            StorId = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "Fruits",
                            StorId = 3
                        });
                });

            modelBuilder.Entity("Super_Market.Proudect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorysId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("PurchasingPrice")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ReciptId")
                        .HasColumnType("int");

                    b.Property<double>("SellingPrice")
                        .HasColumnType("float");

                    b.Property<int?>("Sellinvoceid")
                        .HasColumnType("int");

                    b.Property<int>("Suppliersid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorysId");

                    b.HasIndex("ReciptId");

                    b.HasIndex("Sellinvoceid");

                    b.HasIndex("Suppliersid");

                    b.ToTable("proudcts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategorysId = 1,
                            ExpirationDate = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Milk",
                            ProductionDate = new DateTime(2023, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasingPrice = 11.0,
                            Quantity = 20,
                            SellingPrice = 15.0,
                            Suppliersid = 1
                        },
                        new
                        {
                            Id = 2,
                            CategorysId = 1,
                            ExpirationDate = new DateTime(2023, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cheese",
                            ProductionDate = new DateTime(2023, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasingPrice = 25.0,
                            Quantity = 17,
                            SellingPrice = 30.0,
                            Suppliersid = 1
                        },
                        new
                        {
                            Id = 3,
                            CategorysId = 1,
                            ExpirationDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Egg",
                            ProductionDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasingPrice = 3.0,
                            Quantity = 200,
                            SellingPrice = 5.0,
                            Suppliersid = 1
                        },
                        new
                        {
                            Id = 4,
                            CategorysId = 2,
                            ExpirationDate = new DateTime(2023, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Water",
                            ProductionDate = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasingPrice = 4.0,
                            Quantity = 25,
                            SellingPrice = 6.0,
                            Suppliersid = 2
                        },
                        new
                        {
                            Id = 5,
                            CategorysId = 2,
                            ExpirationDate = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Coffee",
                            ProductionDate = new DateTime(2023, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasingPrice = 7.0,
                            Quantity = 48,
                            SellingPrice = 10.0,
                            Suppliersid = 2
                        },
                        new
                        {
                            Id = 6,
                            CategorysId = 2,
                            ExpirationDate = new DateTime(2023, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Juice",
                            ProductionDate = new DateTime(2023, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasingPrice = 12.0,
                            Quantity = 36,
                            SellingPrice = 16.0,
                            Suppliersid = 2
                        },
                        new
                        {
                            Id = 7,
                            CategorysId = 3,
                            ExpirationDate = new DateTime(2023, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tomato",
                            ProductionDate = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasingPrice = 5.0,
                            Quantity = 70,
                            SellingPrice = 6.0,
                            Suppliersid = 3
                        },
                        new
                        {
                            Id = 8,
                            CategorysId = 3,
                            ExpirationDate = new DateTime(2023, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Potato",
                            ProductionDate = new DateTime(2023, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasingPrice = 12.0,
                            Quantity = 36,
                            SellingPrice = 14.0,
                            Suppliersid = 3
                        },
                        new
                        {
                            Id = 9,
                            CategorysId = 3,
                            ExpirationDate = new DateTime(2023, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "cucumber",
                            ProductionDate = new DateTime(2023, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasingPrice = 15.0,
                            Quantity = 25,
                            SellingPrice = 17.0,
                            Suppliersid = 3
                        });
                });

            modelBuilder.Entity("Super_Market.Recipt", b =>
                {
                    b.Property<int>("bon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bon"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SuppliersId")
                        .HasColumnType("int");

                    b.HasKey("bon");

                    b.HasIndex("SuppliersId");

                    b.ToTable("recipts");
                });

            modelBuilder.Entity("Super_Market.Sellinvoce", b =>
                {
                    b.Property<int>("BonNumberr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BonNumberr"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("PaidMoney")
                        .HasColumnType("float");

                    b.Property<double>("RemainingMoney")
                        .HasColumnType("float");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.Property<string>("casherUserNameUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BonNumberr");

                    b.HasIndex("casherUserNameUserName");

                    b.ToTable("sellinvoces");
                });

            modelBuilder.Entity("Super_Market.Stor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Assiut",
                            Name = "Store1"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Alex",
                            Name = "Store2"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Cairo",
                            Name = "Store3"
                        });
                });

            modelBuilder.Entity("Super_Market.Suppliers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Manar",
                            Phone = "01028574231"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alaa",
                            Phone = "01055688224"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Selevia",
                            Phone = "0104567432"
                        });
                });

            modelBuilder.Entity("Super_Market.Users", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Password")
                        .HasColumnType("int");

                    b.Property<int>("Pos")
                        .HasColumnType("int");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.HasKey("UserName");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            UserName = "Ahmed",
                            Password = 12345,
                            Pos = 0,
                            Salary = 2000f
                        },
                        new
                        {
                            UserName = "Mahmoud",
                            Password = 2555,
                            Pos = 0,
                            Salary = 1000f
                        },
                        new
                        {
                            UserName = "Nada",
                            Password = 54321,
                            Pos = 1,
                            Salary = 3000f
                        });
                });

            modelBuilder.Entity("Super_Market.Categorys", b =>
                {
                    b.HasOne("Super_Market.Stor", "objstor")
                        .WithMany("Categories")
                        .HasForeignKey("StorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("objstor");
                });

            modelBuilder.Entity("Super_Market.Proudect", b =>
                {
                    b.HasOne("Super_Market.Categorys", "category")
                        .WithMany("Products")
                        .HasForeignKey("CategorysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Super_Market.Recipt", "recipt")
                        .WithMany("products")
                        .HasForeignKey("ReciptId");

                    b.HasOne("Super_Market.Sellinvoce", "sellinvoce")
                        .WithMany("Products")
                        .HasForeignKey("Sellinvoceid");

                    b.HasOne("Super_Market.Suppliers", "supplier")
                        .WithMany("products")
                        .HasForeignKey("Suppliersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("recipt");

                    b.Navigation("sellinvoce");

                    b.Navigation("supplier");
                });

            modelBuilder.Entity("Super_Market.Recipt", b =>
                {
                    b.HasOne("Super_Market.Suppliers", "supplier")
                        .WithMany("recipts")
                        .HasForeignKey("SuppliersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("supplier");
                });

            modelBuilder.Entity("Super_Market.Sellinvoce", b =>
                {
                    b.HasOne("Super_Market.Users", "casherUserName")
                        .WithMany("Sellinvos")
                        .HasForeignKey("casherUserNameUserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("casherUserName");
                });

            modelBuilder.Entity("Super_Market.Categorys", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Super_Market.Recipt", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Super_Market.Sellinvoce", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Super_Market.Stor", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Super_Market.Suppliers", b =>
                {
                    b.Navigation("products");

                    b.Navigation("recipts");
                });

            modelBuilder.Entity("Super_Market.Users", b =>
                {
                    b.Navigation("Sellinvos");
                });
#pragma warning restore 612, 618
        }
    }
}
